AWSTemplateFormatVersion: 2010-09-09
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: PlaceHolder

Outputs:
  placeholder:
    Description: "placeholder"
    Value: "placeholder"  